import type { Project } from "@/lib/types";

export const seedProjects: Project[] = [
  {
    id: "lead-time",
    slug: "lead-time-implementation",
    name: "RV6 Lead Time Implementation",
    shortName: "Lead Time",
    code: "R12",
    summary:
      "Deliver a reliable Odoo-to-Shopify lead-time experience from source data through checkout, order confirmation, customer communication, and performance reporting.",
    progress: 65,
    progressLabel: "HQ confirmed",
    status: "Stakeholder UAT",
    health: "attention",
    priority: "Critical",
    phase: "Approval gate",
    owner: "Jemar + Orlando",
    collaborators: ["Rich", "Ling", "Shopify / Odoo teams"],
    lastUpdated: "2026-09-16",
    nextAction: "Schedule the Rich lead-time demo/UAT with Orlando and prepare the proven sandbox flow.",
    blocker: "Production work is gated by stakeholder UAT and approval.",
    accent: "#e3262e",
    outcomes: [
      "Odoo → Shopify lead-time flow technically proven in sandbox",
      "Exact same-SKU synchronization via Shopify Event and n8n",
      "Purchase-time promise preserved through cart and checkout",
      "100% sellable-product coverage and production rollout still pending",
    ],
    milestones: [
      { id: "lt-1", title: "Odoo → Shopify integration", progress: 100, status: "complete", owner: "Jemar + Orlando" },
      { id: "lt-2", title: "Same-SKU synchronization", progress: 100, status: "complete", owner: "Jemar" },
      { id: "lt-3", title: "Storefront, cart & checkout experience", progress: 100, status: "complete", owner: "Jemar" },
      { id: "lt-4", title: "Internal technical demo", progress: 100, status: "complete", owner: "Jemar + Orlando" },
      { id: "lt-5", title: "Rich / stakeholder UAT", progress: 20, status: "in-progress", owner: "Jemar + Orlando", dueLabel: "Schedule next" },
      { id: "lt-6", title: "Full catalog lead-time coverage", progress: 25, status: "pending", owner: "Odoo + Catalog team" },
      { id: "lt-7", title: "Order-confirmation integration", progress: 10, status: "pending", owner: "Jemar" },
      { id: "lt-8", title: "Change notifications & promise-vs-actual reporting", progress: 10, status: "pending", owner: "TBD" },
      { id: "lt-9", title: "Production rollout", progress: 10, status: "blocked", owner: "Jemar", dueLabel: "After UAT" },
    ],
    risks: [
      {
        id: "lt-r1",
        title: "Approval dependency",
        detail: "The technical path is proven, but the production sequence cannot safely start before stakeholder UAT.",
        severity: "high",
        mitigation: "Book the Rich + Orlando demo and use the existing sandbox proof instead of adding scope first.",
        owner: "Jemar",
      },
      {
        id: "lt-r2",
        title: "Catalog completeness",
        detail: "Sandbox proof does not yet establish 100% coverage across sellable products.",
        severity: "medium",
        mitigation: "Run a post-approval audit by variant, mode, shared SKU, and invalid/missing value.",
        owner: "Jemar + Orlando",
      },
    ],
    updates: [
      { id: "lt-u1", date: "2026-09-16", title: "Rich availability confirmed", body: "Monday, Tuesday, Thursday, or Friday are available for the stakeholder demo; Wednesday is unavailable.", type: "progress" },
      { id: "lt-u2", date: "2026-09-16", title: "Overall completion set to 65%", body: "Core sandbox implementation is about 90–95% technically proven; the full Rock remains 65% because rollout and reporting outcomes remain.", type: "decision" },
      { id: "lt-u3", date: "2026-09-16", title: "Daily countdown deferred", body: "Automatic Days decrement is a future enhancement while the Odoo source remains hard-coded.", type: "decision" },
    ],
    sources: [
      { label: "RV6 Lead Time Implementation HQ", kind: "HQ", threadId: "6a845a7e-36ac-83ec-ba74-f1f348c508cd" },
      { label: "RV6 Lead Time Implementation Battle Plan", kind: "Work", threadId: "019febfa-76d7-79b2-acac-87eb0332f974" },
    ],
  },
  {
    id: "folder-structure",
    slug: "folder-structure",
    name: "RV6 Product Assets & Folder Structure",
    shortName: "Folder Structure",
    code: "ASSETS",
    summary:
      "Standardize product and component assets, folder routing, image production, tracking, and the operating SOP that feeds the catalog restructure.",
    progress: 45,
    progressLabel: "Evidence-based estimate",
    status: "In progress",
    health: "attention",
    priority: "High",
    phase: "Asset production",
    owner: "Paul + Jade",
    collaborators: ["Jemar", "Ling", "Danielle"],
    lastUpdated: "2026-09-16",
    nextAction: "Add “Waiting for Stock / Photo” to the tracker and review SOP Revision 4 against the completed Brand Book.",
    blocker: "Raw imagery, stock-dependent photos, and watermarking are incomplete; final SOP approval is pending Brand Book alignment.",
    accent: "#f59e0b",
    outcomes: [
      "Modern RV6 tracker implemented and ready for team use",
      "Product vs component routing made explicit",
      "Revision 4 formatted in the approved SOP layout",
      "Asset collection and watermarking remain the active bottleneck",
    ],
    milestones: [
      { id: "fs-1", title: "Tracker structure and RV6 redesign", progress: 100, status: "complete", owner: "Jemar" },
      { id: "fs-2", title: "Component routing rules", progress: 100, status: "complete", owner: "Paul + Jemar" },
      { id: "fs-3", title: "SOP Revision 4 draft and layout", progress: 85, status: "in-progress", owner: "Jemar", dueLabel: "Brand review pending" },
      { id: "fs-4", title: "Raw image sourcing", progress: 43, status: "in-progress", owner: "Jade" },
      { id: "fs-5", title: "Watermark production", progress: 10, status: "in-progress", owner: "Jade" },
      { id: "fs-6", title: "Folder restructure execution", progress: 50, status: "in-progress", owner: "Paul + Jade" },
      { id: "fs-7", title: "Brand Book alignment and final approval", progress: 20, status: "pending", owner: "Ling + Team" },
    ],
    risks: [
      {
        id: "fs-r1",
        title: "Asset availability",
        detail: "Some product photos cannot be produced until physical stock is available and several images still need product confirmation.",
        severity: "high",
        mitigation: "Track stock/photo wait states separately from missing or rejected assets.",
        owner: "Jade",
      },
      {
        id: "fs-r2",
        title: "Source-of-truth decision",
        detail: "Odoo storage for drawings and revision-controlled documents is exploratory, not approved.",
        severity: "medium",
        mitigation: "Keep the current SOP unchanged until Rich, Ling, and Orlando decide system ownership.",
        owner: "Paul",
      },
    ],
    updates: [
      { id: "fs-u1", date: "2026-09-16", title: "Asset progress reported", body: "43.15% of requested raw images are received and watermarking is approximately 10% complete.", type: "progress" },
      { id: "fs-u2", date: "2026-09-16", title: "Brand Book now complete", body: "SOP Revision 4 should be checked against the Brand Book before final approval.", type: "approval" },
      { id: "fs-u3", date: "2026-09-16", title: "Catalog dependency confirmed", body: "Folder restructuring and watermarking are prerequisites for the broader Shopify catalog revamp.", type: "blocker" },
    ],
    sources: [
      { label: "RV6 Folder Structure HQ", kind: "HQ", threadId: "6a7b2175-4234-83ec-8dbb-8a77f099ca0e" },
      { label: "RV6 Folder Structure", kind: "Work", threadId: "019fece2-4ce6-7883-aa62-1e59221cc735" },
    ],
  },
  {
    id: "blog",
    slug: "blog-implementation",
    name: "RV6 Blog Implementation",
    shortName: "Blog",
    code: "CONTENT",
    summary:
      "Launch a professional RV6 Updates experience with approved article presentation, SEO readiness, safe review gates, and post-launch measurement.",
    progress: 85,
    progressLabel: "HQ confirmed",
    status: "Awaiting content",
    health: "blocked",
    priority: "High",
    phase: "Content & approval",
    owner: "Jemar",
    collaborators: ["Rich", "Ling", "Orlando"],
    lastUpdated: "2026-09-16",
    nextAction: "Obtain Rich’s sandbox review and first article content, then professionalize the article and complete article-specific SEO.",
    blocker: "Waiting on Rich’s review, topics, and source content before final SEO and live deployment.",
    accent: "#22c55e",
    outcomes: [
      "Sandbox blog experience implemented and visually QA’d",
      "Ling approved the current direction",
      "Article page accessibility and responsive issues resolved",
      "Real content, final SEO, Rich approval, and production deployment remain",
    ],
    milestones: [
      { id: "bl-1", title: "Sandbox blog architecture", progress: 100, status: "complete", owner: "Jemar" },
      { id: "bl-2", title: "Responsive UI and accessibility QA", progress: 100, status: "complete", owner: "Jemar" },
      { id: "bl-3", title: "Ling direction approval", progress: 100, status: "complete", owner: "Ling" },
      { id: "bl-4", title: "Rich sandbox review", progress: 25, status: "blocked", owner: "Rich" },
      { id: "bl-5", title: "First article content", progress: 10, status: "blocked", owner: "Rich" },
      { id: "bl-6", title: "Article SEO package", progress: 35, status: "pending", owner: "Jemar" },
      { id: "bl-7", title: "Final approval and live deployment", progress: 10, status: "pending", owner: "Rich + Jemar" },
    ],
    risks: [
      {
        id: "bl-r1",
        title: "Content dependency",
        detail: "Development is effectively complete, but the project cannot cross the finish line without source content and executive review.",
        severity: "high",
        mitigation: "Request one article or structured topic notes and process it through a review-first workflow.",
        owner: "Rich",
      },
      {
        id: "bl-r2",
        title: "Measurement handoff",
        detail: "The marketing dashboard must distinguish organic blog traffic from paid Google/Facebook traffic.",
        severity: "low",
        mitigation: "Coordinate Shopify traffic data with Orlando’s separate dashboard workstream.",
        owner: "Jemar + Orlando",
      },
    ],
    updates: [
      { id: "bl-u1", date: "2026-09-16", title: "Content commitment recorded", body: "Rich said he has blog posts to organize and send for professional formatting.", type: "progress" },
      { id: "bl-u2", date: "2026-09-16", title: "Status remains 85%", body: "Sandbox and QA are complete; content and approval are the active gates.", type: "decision" },
      { id: "bl-u3", date: "2026-09-05", title: "Article polish completed", body: "Breadcrumb contrast, footer navigation, focus treatment, and mobile behavior were corrected in sandbox.", type: "progress" },
    ],
    sources: [
      { label: "RV6 Blog Project HQ", kind: "HQ", threadId: "6a8c96e5-1160-83ec-8754-d1daff3c7d73" },
      { label: "RV6 Blog Implementation", kind: "Work", threadId: "01a034f9-fb3f-73a2-9df0-f07da1e3f15d" },
    ],
  },
  {
    id: "ai-support",
    slug: "ai-customer-support",
    name: "RV6 AI Customer Support Automation",
    shortName: "AI Support",
    code: "AI OPS",
    summary:
      "Build a controlled AI support workflow that classifies inquiries, retrieves approved knowledge and live order facts, protects customer data, and escalates safely.",
    progress: 60,
    progressLabel: "HQ confirmed",
    status: "Phase A integration",
    health: "on-track",
    priority: "Critical",
    phase: "Integration & coverage",
    owner: "Jemar",
    collaborators: ["Orlando", "Support team", "Leadership"],
    lastUpdated: "2026-09-16",
    nextAction: "Integrate the validated Shopify Order Status path into the frozen Phase A branch and expand approved KB coverage.",
    blocker: "Odoo enrichment depends on Orlando’s planned Pending Order Tracker and a confirmed data contract.",
    accent: "#8b5cf6",
    outcomes: [
      "Core intake, deterministic KB routing, and safety controls validated",
      "Message-level idempotency and evidence isolation frozen",
      "Shopify read-only order-status proof validated",
      "Production autosend remains intentionally disabled",
    ],
    milestones: [
      { id: "ai-1", title: "Customer intake and classification", progress: 100, status: "complete", owner: "Jemar" },
      { id: "ai-2", title: "Phase A KB routing checkpoint", progress: 100, status: "complete", owner: "Jemar" },
      { id: "ai-3", title: "Shopify order-status proof", progress: 100, status: "complete", owner: "Jemar" },
      { id: "ai-4", title: "Phase A Shopify integration", progress: 35, status: "in-progress", owner: "Jemar" },
      { id: "ai-5", title: "Approved KB coverage audit", progress: 40, status: "in-progress", owner: "Support team" },
      { id: "ai-6", title: "Odoo enrichment contract", progress: 15, status: "blocked", owner: "Jemar + Orlando" },
      { id: "ai-7", title: "Controlled leadership demo", progress: 20, status: "pending", owner: "Jemar" },
      { id: "ai-8", title: "Production readiness and rollout", progress: 5, status: "pending", owner: "Leadership" },
    ],
    risks: [
      {
        id: "ai-r1",
        title: "Odoo dependency",
        detail: "Shopify can state fulfillment status but cannot reliably explain manufacturing blockers or forecast dates.",
        severity: "high",
        mitigation: "Align the AI data contract with Orlando’s planned Pending Order Tracker instead of building parallel logic.",
        owner: "Jemar + Orlando",
      },
      {
        id: "ai-r2",
        title: "Knowledge coverage",
        detail: "The routing engine is proven, but approved support answers do not yet cover the full support surface.",
        severity: "medium",
        mitigation: "Audit real inquiry categories, approve authoritative answers, and test each route before enabling broader use.",
        owner: "Support team",
      },
    ],
    updates: [
      { id: "ai-u1", date: "2026-09-16", title: "Completion reaffirmed at 60%", body: "Core architecture is validated; integration, coverage, Odoo enrichment, and demo work remain.", type: "decision" },
      { id: "ai-u2", date: "2026-09-16", title: "Pending Order Tracker dependency identified", body: "The planned Odoo view may provide delay reason, blocking component, and forecast data needed by AI responses.", type: "blocker" },
      { id: "ai-u3", date: "2026-08-26", title: "Phase A checkpoint frozen", body: "KB routing integration passed, remained inactive, and preserved the production safety boundary.", type: "approval" },
    ],
    sources: [
      { label: "RV6 AI Automation HQ", kind: "HQ", threadId: "6a7487df-4284-83ec-bf4b-29a123f18c37" },
      { label: "RV6 AI Customer Support Automation", kind: "Work", threadId: "019fb923-93fa-76e2-9ae0-74c5e5581741" },
    ],
  },
  {
    id: "website",
    slug: "website-restructure",
    name: "RV6 Website Restructure",
    shortName: "Website Restructure",
    code: "R19",
    summary:
      "Create one trustworthy catalog across Odoo, product assets, Shopify, content, SEO, and long-term operational ownership.",
    progress: 15,
    progressLabel: "Conservative estimate",
    status: "Planning",
    health: "planning",
    priority: "Critical",
    phase: "Discovery & dependencies",
    owner: "Paul",
    collaborators: ["Jemar", "Jade", "Rich", "Ling", "Orlando"],
    lastUpdated: "2026-09-16",
    nextAction: "Schedule and prepare the Rich/Ling website-content and catalog decision meeting with Paul and Orlando.",
    blocker: "Catalog implementation is waiting on folder/image work and additional product direction from Rich and Ling.",
    accent: "#3b82f6",
    outcomes: [
      "Program scope and six workstreams defined",
      "Role boundaries and source-of-truth hierarchy established",
      "Catalog implementation itself has not started",
      "Folder structure, images, and leadership decisions are prerequisite inputs",
    ],
    milestones: [
      { id: "wr-1", title: "Program scope and workstreams", progress: 100, status: "complete", owner: "Jemar + Paul" },
      { id: "wr-2", title: "Roles and source-of-truth model", progress: 80, status: "in-progress", owner: "Paul + Jemar" },
      { id: "wr-3", title: "Leadership requirements meeting", progress: 15, status: "pending", owner: "Paul + Jemar" },
      { id: "wr-4", title: "Product master and catalog audit", progress: 5, status: "blocked", owner: "Paul + Product owners" },
      { id: "wr-5", title: "Taxonomy, collections and navigation", progress: 5, status: "blocked", owner: "Paul + Jemar" },
      { id: "wr-6", title: "Pilot category migration", progress: 0, status: "pending", owner: "Team" },
      { id: "wr-7", title: "SEO, content and technical implementation", progress: 0, status: "pending", owner: "Jemar" },
      { id: "wr-8", title: "Batch rollout and governance", progress: 0, status: "pending", owner: "Team" },
    ],
    risks: [
      {
        id: "wr-r1",
        title: "Approval bottlenecks",
        detail: "If every product, image, price, and navigation choice returns to the same leaders, delivery will slow significantly.",
        severity: "high",
        mitigation: "Agree on an approval matrix separating product, operational, asset, and technical decisions.",
        owner: "Paul",
      },
      {
        id: "wr-r2",
        title: "Scope expansion",
        detail: "Catalog cleanup, blog, FAQ, AI discoverability, lead time, and marketing can become one unfinishable program.",
        severity: "high",
        mitigation: "Keep connected projects linked but separately managed; pilot one representative catalog category first.",
        owner: "Paul + Jemar",
      },
    ],
    updates: [
      { id: "wr-u1", date: "2026-09-16", title: "Catalog revamp remains in planning", body: "Paul confirmed implementation has not started because folder restructuring and watermarking are being prioritized.", type: "blocker" },
      { id: "wr-u2", date: "2026-09-16", title: "Leadership meeting required", body: "Paul, Jemar, and Orlando were asked to schedule next-week time with Rich for website and catalog direction.", type: "progress" },
      { id: "wr-u3", date: "2026-09-16", title: "Blemished product rule confirmed", body: "Blemished items should use separate SKUs; Danielle will create the list and part numbers.", type: "decision" },
    ],
    sources: [
      { label: "RV6 Website Restructure HQ", kind: "HQ", threadId: "6aa9500d-6c9c-83ec-96cd-4f6e5f813a3f" },
      { label: "Coordinate RV6 website restructure", kind: "Work", threadId: "01a0a569-ef91-7a42-b511-86dea531a75a" },
    ],
  },
];

export const reportAsOf = "2026-09-16";
